### ISSUE TITLE
Details pane versioning incorrect

### ISSUE THREAD

**Issue by jaredauty** [shotgunsoftware/tk-multi-breakdown2#30]
Heya,

Considering switching to the new breakdown tool but ran into this annoying issue.
Seems like the versions are sorted alphanumerically in the details pane so for instance you end up with v9 coming ahead of v39.

It looks like an issue with self._file_history_proxy_model in dialog.py but I haven't had time to fix it.

![image](https://user-images.githubusercontent.com/3268451/170589395-41646219-c49c-46b1-814d-42405787fb65.png)

You can ignore the duplicate versions (it's a testing context and there's duplicate publish files for some reason).
Thanks

**Comment by rob-aitchison** [comment]
Thanks for logging this issue @jaredauty , we will look into this further.
