### ISSUE TITLE
Item details not legible in Houdini

### ISSUE THREAD

**Issue by RicardoMusch** [shotgunsoftware/tk-multi-breakdown2#52]
In Houdini 19.5 (likely also below) the background of the item makes the text inside very hard to read.

![image](https://github.com/shotgunsoftware/tk-multi-breakdown2/assets/54025297/21acb60c-38fe-483d-bb65-2ec857ffd774)

**Comment by staceyoue** [comment]
@RicardoMusch I believe this is a duplicate issue of https://github.com/shotgunsoftware/tk-multi-breakdown2/issues/45 and https://github.com/shotgunsoftware/tk-multi-breakdown2/issues/37.

You need to override the `ui_config_advanced.py` hook method to change the item background color. Seems like the `light` palette works best for Houdini by other user comments.
