### ISSUE TITLE
Feature: Actions in Breakdown

### ISSUE THREAD

**Issue by simonDarmstadt** [shotgunsoftware/tk-multi-breakdown2#54]
Hey there,

I am working at Pixomondo and in our pipeline we "patched" the breakdown to support custom actions.

![grafik](https://github.com/shotgunsoftware/tk-multi-breakdown2/assets/17123554/0345ecb0-46cb-45c1-8355-e8af80bdccd6)

In our `maya_scene_operations.py` we can add custom actions by adding them as extra_attr:

```
refs.append(
    {
        "node_name": reference_node.name(),
        "node_type": "reference",
        "path": ref_file_path,
        "extra_data": {
            "actions": {
                LABEL_REMOVE: {
                    "function": remove_reference,
                    "force_update": True,  # Needed for v0.2.4 since it lacks update functionaltiy and we patched it in.
                },
                LABEL_SELECT: {
                    "function": select_reference_top_nodes,
                    "force_update": False,
                }
            }
        }
    }
)
```

My current question is: Is there already some action-support like in SG Loader planned for the breakdown2?
Or is that feature something you would like for future releases? For us it would be an option to contribute to the project for pushing the official support.

Best,
Simon

**Comment by staceyoue** [comment]
Hi @simonDarmstadt, at the moment there is nothing planned to support actions (like in Loader). I have logged a ticket for this, but also feel free to create a PR for this feature.
